# fly.toml app configuration file generated for ai-template on 2023-06-13T10:46:13+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-template"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
