# fly.toml app configuration file generated for ai-getting-started on 2023-06-16T14:37:45+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-getting-started"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
